"""Database initialization and helpers for OfferGo."""

from __future__ import annotations

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import psycopg
    from psycopg.rows import dict_row
except Exception:  # pragma: no cover - optional dependency during local sqlite runs
    psycopg = None
    dict_row = None


SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS visitors (
        visitor_id TEXT PRIMARY KEY,
        first_seen_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL,
        user_agent TEXT NOT NULL DEFAULT ''
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS visitor_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        visitor_id TEXT NOT NULL,
        path TEXT NOT NULL,
        user_agent TEXT NOT NULL DEFAULT '',
        visited_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS questions (
        id TEXT PRIMARY KEY,
        domain TEXT NOT NULL,
        section TEXT NOT NULL DEFAULT '',
        category TEXT NOT NULL DEFAULT '',
        difficulty TEXT NOT NULL DEFAULT 'mid',
        question TEXT NOT NULL,
        summary TEXT NOT NULL DEFAULT '',
        source_title TEXT NOT NULL DEFAULT '',
        source_url TEXT NOT NULL DEFAULT '',
        tags_json TEXT NOT NULL DEFAULT '[]',
        answer_points_json TEXT NOT NULL DEFAULT '[]',
        follow_ups_json TEXT NOT NULL DEFAULT '[]',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS question_progress (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        visitor_id TEXT NOT NULL DEFAULT '',
        user_id TEXT NOT NULL DEFAULT '',
        question_id TEXT NOT NULL,
        favorite INTEGER NOT NULL DEFAULT 0,
        mastered INTEGER NOT NULL DEFAULT 0,
        practice_count INTEGER NOT NULL DEFAULT 0,
        last_practiced_at TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(visitor_id, question_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS learning_progress (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        scope_type TEXT NOT NULL,
        scope_id TEXT NOT NULL,
        question_id TEXT NOT NULL,
        favorite INTEGER NOT NULL DEFAULT 0,
        mastered INTEGER NOT NULL DEFAULT 0,
        practice_count INTEGER NOT NULL DEFAULT 0,
        last_practiced_at TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(scope_type, scope_id, question_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        username TEXT NOT NULL,
        username_normalized TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        password_salt TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS auth_sessions (
        session_id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        expires_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS resume_sessions (
        resume_id TEXT PRIMARY KEY,
        resume_text TEXT NOT NULL,
        filename TEXT NOT NULL,
        target_role TEXT NOT NULL,
        target_stack TEXT NOT NULL DEFAULT '',
        target_jd TEXT NOT NULL DEFAULT '',
        selected_domain TEXT NOT NULL DEFAULT '',
        review_json TEXT NOT NULL,
        mode_label TEXT NOT NULL,
        ai_error TEXT NOT NULL DEFAULT '',
        keywords_json TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS interview_answers (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        scope_type TEXT NOT NULL,
        scope_id TEXT NOT NULL,
        question_id TEXT NOT NULL,
        answer_text TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(scope_type, scope_id, question_id)
    )
    """,
]

POSTGRES_SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS visitors (
        visitor_id TEXT PRIMARY KEY,
        first_seen_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL,
        user_agent TEXT NOT NULL DEFAULT ''
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS visitor_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        visitor_id TEXT NOT NULL,
        path TEXT NOT NULL,
        user_agent TEXT NOT NULL DEFAULT '',
        visited_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS questions (
        id TEXT PRIMARY KEY,
        domain TEXT NOT NULL,
        section TEXT NOT NULL DEFAULT '',
        category TEXT NOT NULL DEFAULT '',
        difficulty TEXT NOT NULL DEFAULT 'mid',
        question TEXT NOT NULL,
        summary TEXT NOT NULL DEFAULT '',
        source_title TEXT NOT NULL DEFAULT '',
        source_url TEXT NOT NULL DEFAULT '',
        tags_json TEXT NOT NULL DEFAULT '[]',
        answer_points_json TEXT NOT NULL DEFAULT '[]',
        follow_ups_json TEXT NOT NULL DEFAULT '[]',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS question_progress (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        visitor_id TEXT NOT NULL DEFAULT '',
        user_id TEXT NOT NULL DEFAULT '',
        question_id TEXT NOT NULL,
        favorite INTEGER NOT NULL DEFAULT 0,
        mastered INTEGER NOT NULL DEFAULT 0,
        practice_count INTEGER NOT NULL DEFAULT 0,
        last_practiced_at TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        UNIQUE(visitor_id, question_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS learning_progress (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        scope_type TEXT NOT NULL,
        scope_id TEXT NOT NULL,
        question_id TEXT NOT NULL,
        favorite INTEGER NOT NULL DEFAULT 0,
        mastered INTEGER NOT NULL DEFAULT 0,
        practice_count INTEGER NOT NULL DEFAULT 0,
        last_practiced_at TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        UNIQUE(scope_type, scope_id, question_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        username TEXT NOT NULL,
        username_normalized TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        password_salt TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS auth_sessions (
        session_id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        expires_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS resume_sessions (
        resume_id TEXT PRIMARY KEY,
        resume_text TEXT NOT NULL,
        filename TEXT NOT NULL,
        target_role TEXT NOT NULL,
        target_stack TEXT NOT NULL DEFAULT '',
        target_jd TEXT NOT NULL DEFAULT '',
        selected_domain TEXT NOT NULL DEFAULT '',
        review_json TEXT NOT NULL,
        mode_label TEXT NOT NULL,
        ai_error TEXT NOT NULL DEFAULT '',
        keywords_json TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS interview_answers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        scope_type TEXT NOT NULL,
        scope_id TEXT NOT NULL,
        question_id TEXT NOT NULL,
        answer_text TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        UNIQUE(scope_type, scope_id, question_id)
    )
    """,
]


def _is_postgres_target(db_target: Path | str) -> bool:
    return isinstance(db_target, str) and db_target.startswith(("postgres://", "postgresql://"))


class DatabaseConnection:
    def __init__(self, raw_connection, backend: str):
        self._raw_connection = raw_connection
        self.backend = backend

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type is None:
                self._raw_connection.commit()
            else:
                self._raw_connection.rollback()
        finally:
            self._raw_connection.close()

    def _prepare_sql(self, sql: str) -> str:
        if self.backend == "postgres":
            return sql.replace("?", "%s")
        return sql

    def execute(self, sql: str, params: tuple[Any, ...] | list[Any] = ()):
        return self._raw_connection.execute(self._prepare_sql(sql), params)

    def commit(self) -> None:
        self._raw_connection.commit()

    def rollback(self) -> None:
        self._raw_connection.rollback()

    def close(self) -> None:
        self._raw_connection.close()


def connect_sqlite(db_target: Path | str):
    if _is_postgres_target(db_target):
        if psycopg is None or dict_row is None:
            raise RuntimeError("PostgreSQL support requires psycopg; install dependencies first")
        connection = psycopg.connect(str(db_target), row_factory=dict_row)
        return DatabaseConnection(connection, "postgres")

    db_path = Path(db_target)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(db_path)
    connection.row_factory = sqlite3.Row
    return DatabaseConnection(connection, "sqlite")


def _schema_for(db_target: Path | str) -> list[str]:
    return POSTGRES_SCHEMA_STATEMENTS if _is_postgres_target(db_target) else SCHEMA_STATEMENTS


def initialize_database(db_path: Path | str) -> None:
    with connect_sqlite(db_path) as conn:
        for statement in _schema_for(db_path):
            conn.execute(statement)
        migrate_legacy_progress(conn)


def ensure_questions_seeded(db_path: Path | str, questions_path: Path) -> int:
    with connect_sqlite(db_path) as conn:
        existing_row = conn.execute("SELECT COUNT(*) AS existing_count FROM questions").fetchone()
        existing_count = existing_row["existing_count"] if existing_row else 0
        if int(existing_count or 0) > 0:
            return 0

    with questions_path.open("r", encoding="utf-8") as file:
        payload = json.load(file)
    return upsert_questions_from_payload(db_path, payload)


def migrate_legacy_progress(conn) -> None:
    conn.execute(
        """
        INSERT INTO learning_progress (
            scope_type,
            scope_id,
            question_id,
            favorite,
            mastered,
            practice_count,
            last_practiced_at,
            created_at,
            updated_at
        )
        SELECT
            'visitor',
            visitor_id,
            question_id,
            favorite,
            mastered,
            practice_count,
            last_practiced_at,
            created_at,
            updated_at
        FROM question_progress
        WHERE visitor_id <> ''
        ON CONFLICT(scope_type, scope_id, question_id) DO NOTHING
        """
    )


def upsert_questions_from_payload(db_path: Path | str, payload: dict[str, Any]) -> int:
    questions = payload.get("questions", [])
    count = 0
    with connect_sqlite(db_path) as conn:
        for item in questions:
            conn.execute(
                """
                INSERT INTO questions (
                    id, domain, section, category, difficulty, question, summary,
                    source_title, source_url, tags_json, answer_points_json, follow_ups_json
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(id) DO UPDATE SET
                    domain=excluded.domain,
                    section=excluded.section,
                    category=excluded.category,
                    difficulty=excluded.difficulty,
                    question=excluded.question,
                    summary=excluded.summary,
                    source_title=excluded.source_title,
                    source_url=excluded.source_url,
                    tags_json=excluded.tags_json,
                    answer_points_json=excluded.answer_points_json,
                    follow_ups_json=excluded.follow_ups_json
                """,
                (
                    item.get("id", ""),
                    item.get("domain", ""),
                    item.get("section", ""),
                    item.get("category", ""),
                    item.get("difficulty", "mid"),
                    item.get("question", ""),
                    item.get("summary", ""),
                    item.get("sourceTitle", ""),
                    item.get("sourceUrl", ""),
                    json.dumps(item.get("tags", []), ensure_ascii=False),
                    json.dumps(item.get("answerPoints", []), ensure_ascii=False),
                    json.dumps(item.get("followUps", []), ensure_ascii=False),
                ),
            )
            count += 1
    return count


def load_questions_payload(db_path: Path | str) -> dict[str, Any]:
    with connect_sqlite(db_path) as conn:
        rows = conn.execute(
            """
            SELECT
                id, domain, section, category, difficulty, question, summary,
                source_title, source_url, tags_json, answer_points_json, follow_ups_json
            FROM questions
            ORDER BY domain, category, id
            """
        ).fetchall()

    questions: list[dict[str, Any]] = []
    domain_counts: dict[str, dict[str, int]] = {}

    for row in rows:
        domain = row["domain"] or "other"
        category = row["category"] or "other"
        domain_counts.setdefault(domain, {})
        domain_counts[domain][category] = domain_counts[domain].get(category, 0) + 1

        questions.append(
            {
                "id": row["id"],
                "domain": domain,
                "section": row["section"] or "",
                "question": row["question"] or "",
                "category": category,
                "difficulty": row["difficulty"] or "mid",
                "tags": json.loads(row["tags_json"] or "[]"),
                "answerPoints": json.loads(row["answer_points_json"] or "[]"),
                "followUps": json.loads(row["follow_ups_json"] or "[]"),
                "summary": row["summary"] or "",
                "sourceTitle": row["source_title"] or "",
                "sourceUrl": row["source_url"] or "",
            }
        )

    return {
        "meta": {
            "total": len(questions),
            "domains": domain_counts,
        },
        "questions": questions,
    }


def _resolve_scope(visitor_id: str = "", user_id: str = "") -> tuple[str, str]:
    if user_id:
        return "user", user_id
    return "visitor", visitor_id


def _load_progress_payload(conn: sqlite3.Connection, scope_type: str, scope_id: str) -> dict[str, Any]:
    rows = conn.execute(
        """
        SELECT question_id, favorite, mastered, practice_count, last_practiced_at
        FROM learning_progress
        WHERE scope_type = ? AND scope_id = ?
        """,
        (scope_type, scope_id),
    ).fetchall()

    favorites: list[str] = []
    mastered: list[str] = []
    practice: dict[str, dict[str, Any]] = {}

    for row in rows:
        question_id = row["question_id"]
        if row["favorite"]:
            favorites.append(question_id)
        if row["mastered"]:
            mastered.append(question_id)
        if row["practice_count"] or row["last_practiced_at"]:
            practice[question_id] = {
                "practiceCount": int(row["practice_count"] or 0),
                "lastPracticedAt": row["last_practiced_at"] or "",
            }

    return {
        "ok": True,
        "favorites": favorites,
        "mastered": mastered,
        "practice": practice,
    }


def get_user_progress_payload(db_path: Path, visitor_id: str = "", *, user_id: str = "") -> dict[str, Any]:
    scope_type, scope_id = _resolve_scope(visitor_id, user_id)
    with connect_sqlite(db_path) as conn:
        return _load_progress_payload(conn, scope_type, scope_id)


def upsert_question_progress(
    db_path: Path,
    visitor_id: str,
    question_id: str,
    *,
    user_id: str = "",
    favorite: bool | None = None,
    mastered: bool | None = None,
    practiced_at: str | None = None,
) -> dict[str, Any]:
    scope_type, scope_id = _resolve_scope(visitor_id, user_id)

    with connect_sqlite(db_path) as conn:
        existing = conn.execute(
            """
            SELECT favorite, mastered, practice_count, last_practiced_at
            FROM learning_progress
            WHERE scope_type = ? AND scope_id = ? AND question_id = ?
            """,
            (scope_type, scope_id, question_id),
        ).fetchone()

        current_favorite = int(existing["favorite"]) if existing else 0
        current_mastered = int(existing["mastered"]) if existing else 0
        current_practice_count = int(existing["practice_count"]) if existing else 0
        current_last_practiced_at = existing["last_practiced_at"] if existing else ""

        next_favorite = current_favorite if favorite is None else int(bool(favorite))
        next_mastered = current_mastered if mastered is None else int(bool(mastered))
        next_practice_count = current_practice_count + (1 if practiced_at else 0)
        next_last_practiced_at = practiced_at or current_last_practiced_at

        conn.execute(
            """
            INSERT INTO learning_progress (
                scope_type, scope_id, question_id, favorite, mastered, practice_count, last_practiced_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT(scope_type, scope_id, question_id) DO UPDATE SET
                favorite=excluded.favorite,
                mastered=excluded.mastered,
                practice_count=excluded.practice_count,
                last_practiced_at=excluded.last_practiced_at,
                updated_at=CURRENT_TIMESTAMP
            """,
            (
                scope_type,
                scope_id,
                question_id,
                next_favorite,
                next_mastered,
                next_practice_count,
                next_last_practiced_at,
            ),
        )

    return {
        "ok": True,
        "questionId": question_id,
        "favorite": bool(next_favorite),
        "mastered": bool(next_mastered),
        "practiceCount": next_practice_count,
        "lastPracticedAt": next_last_practiced_at,
    }


def sync_user_progress(
    db_path: Path,
    visitor_id: str,
    favorites: list[str],
    mastered: list[str],
    *,
    user_id: str = "",
) -> dict[str, Any]:
    scope_type, scope_id = _resolve_scope(visitor_id, user_id)
    favorites_set = set(favorites or [])
    mastered_set = set(mastered or [])
    all_ids = favorites_set | mastered_set

    with connect_sqlite(db_path) as conn:
        for question_id in all_ids:
            conn.execute(
                """
                INSERT INTO learning_progress (
                    scope_type, scope_id, question_id, favorite, mastered, updated_at
                )
                VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT(scope_type, scope_id, question_id) DO UPDATE SET
                    favorite=excluded.favorite,
                    mastered=excluded.mastered,
                    updated_at=CURRENT_TIMESTAMP
                """,
                (
                    scope_type,
                    scope_id,
                    question_id,
                    int(question_id in favorites_set),
                    int(question_id in mastered_set),
                ),
            )
        return _load_progress_payload(conn, scope_type, scope_id)


def merge_progress_into_user(db_path: Path, visitor_id: str, user_id: str) -> dict[str, Any]:
    if not visitor_id or not user_id:
        return get_user_progress_payload(db_path, user_id=user_id)

    with connect_sqlite(db_path) as conn:
        rows = conn.execute(
            """
            SELECT question_id, favorite, mastered, practice_count, last_practiced_at
            FROM learning_progress
            WHERE scope_type = 'visitor' AND scope_id = ?
            """,
            (visitor_id,),
        ).fetchall()

        for row in rows:
            existing = conn.execute(
                """
                SELECT favorite, mastered, practice_count, last_practiced_at
                FROM learning_progress
                WHERE scope_type = 'user' AND scope_id = ? AND question_id = ?
                """,
                (user_id, row["question_id"]),
            ).fetchone()

            favorite = max(int(row["favorite"] or 0), int(existing["favorite"] or 0) if existing else 0)
            mastered = max(int(row["mastered"] or 0), int(existing["mastered"] or 0) if existing else 0)
            practice_count = int(row["practice_count"] or 0) + (int(existing["practice_count"] or 0) if existing else 0)
            last_practiced_at = max(
                row["last_practiced_at"] or "",
                (existing["last_practiced_at"] or "") if existing else "",
            )

            conn.execute(
                """
                INSERT INTO learning_progress (
                    scope_type, scope_id, question_id, favorite, mastered, practice_count, last_practiced_at, updated_at
                )
                VALUES ('user', ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT(scope_type, scope_id, question_id) DO UPDATE SET
                    favorite=excluded.favorite,
                    mastered=excluded.mastered,
                    practice_count=excluded.practice_count,
                    last_practiced_at=excluded.last_practiced_at,
                    updated_at=CURRENT_TIMESTAMP
                """,
                (
                    user_id,
                    row["question_id"],
                    favorite,
                    mastered,
                    practice_count,
                    last_practiced_at,
                ),
            )

        conn.execute(
            """
            DELETE FROM learning_progress
            WHERE scope_type = 'visitor' AND scope_id = ?
            """,
            (visitor_id,),
        )
        return _load_progress_payload(conn, "user", user_id)


def _load_interview_answers_payload(conn, scope_type: str, scope_id: str) -> dict[str, Any]:
    rows = conn.execute(
        """
        SELECT question_id, answer_text, updated_at
        FROM interview_answers
        WHERE scope_type = ? AND scope_id = ?
        ORDER BY updated_at DESC, question_id ASC
        """,
        (scope_type, scope_id),
    ).fetchall()

    answers: dict[str, dict[str, Any]] = {}
    for row in rows:
        question_id = row["question_id"]
        answers[question_id] = {
            "answer": row["answer_text"] or "",
            "updatedAt": normalize_db_timestamp(row["updated_at"]),
        }

    return {"ok": True, "interviewAnswers": answers}


def get_interview_answers_payload(db_path: Path | str, visitor_id: str = "", *, user_id: str = "") -> dict[str, Any]:
    scope_type, scope_id = _resolve_scope(visitor_id, user_id)
    with connect_sqlite(db_path) as conn:
        return _load_interview_answers_payload(conn, scope_type, scope_id)


def upsert_interview_answer(
    db_path: Path | str,
    visitor_id: str,
    question_id: str,
    answer: str,
    *,
    user_id: str = "",
    updated_at: str = "",
) -> dict[str, Any]:
    scope_type, scope_id = _resolve_scope(visitor_id, user_id)
    next_updated_at = updated_at or datetime.now(timezone.utc).isoformat()
    next_answer = str(answer or "")

    with connect_sqlite(db_path) as conn:
        conn.execute(
            """
            INSERT INTO interview_answers (
                scope_type,
                scope_id,
                question_id,
                answer_text,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(scope_type, scope_id, question_id) DO UPDATE SET
                answer_text=excluded.answer_text,
                updated_at=excluded.updated_at
            """,
            (
                scope_type,
                scope_id,
                question_id,
                next_answer,
                next_updated_at,
                next_updated_at,
            ),
        )

    return {
        "ok": True,
        "questionId": question_id,
        "answer": next_answer,
        "updatedAt": next_updated_at,
    }


def merge_interview_answers_into_user(db_path: Path | str, visitor_id: str, user_id: str) -> dict[str, Any]:
    if not visitor_id or not user_id:
        return get_interview_answers_payload(db_path, user_id=user_id)

    with connect_sqlite(db_path) as conn:
        rows = conn.execute(
            """
            SELECT question_id, answer_text, updated_at
            FROM interview_answers
            WHERE scope_type = 'visitor' AND scope_id = ?
            """,
            (visitor_id,),
        ).fetchall()

        for row in rows:
            existing = conn.execute(
                """
                SELECT answer_text, updated_at
                FROM interview_answers
                WHERE scope_type = 'user' AND scope_id = ? AND question_id = ?
                """,
                (user_id, row["question_id"]),
            ).fetchone()

            chosen_answer = row["answer_text"] or ""
            chosen_updated_at = normalize_db_timestamp(row["updated_at"])

            if existing:
                existing_updated_at = normalize_db_timestamp(existing["updated_at"])
                if existing_updated_at >= chosen_updated_at:
                    chosen_answer = existing["answer_text"] or ""
                    chosen_updated_at = existing_updated_at

            conn.execute(
                """
                INSERT INTO interview_answers (
                    scope_type,
                    scope_id,
                    question_id,
                    answer_text,
                    created_at,
                    updated_at
                )
                VALUES ('user', ?, ?, ?, CURRENT_TIMESTAMP, ?)
                ON CONFLICT(scope_type, scope_id, question_id) DO UPDATE SET
                    answer_text=excluded.answer_text,
                    updated_at=excluded.updated_at
                """,
                (
                    user_id,
                    row["question_id"],
                    chosen_answer,
                    chosen_updated_at or datetime.now(timezone.utc).isoformat(),
                ),
            )

        conn.execute(
            """
            DELETE FROM interview_answers
            WHERE scope_type = 'visitor' AND scope_id = ?
            """,
            (visitor_id,),
        )
        return _load_interview_answers_payload(conn, "user", user_id)


def create_user(
    db_path: Path,
    *,
    user_id: str,
    username: str,
    username_normalized: str,
    password_hash: str,
    password_salt: str,
    now_iso: str,
) -> dict[str, Any]:
    with connect_sqlite(db_path) as conn:
        conn.execute(
            """
            INSERT INTO users (id, username, username_normalized, password_hash, password_salt, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (user_id, username, username_normalized, password_hash, password_salt, now_iso, now_iso),
        )
        row = conn.execute(
            """
            SELECT id, username, created_at
            FROM users
            WHERE id = ?
            """,
            (user_id,),
        ).fetchone()
    return _serialize_user(row)


def get_user_by_username(db_path: Path, username_normalized: str) -> dict[str, Any] | None:
    with connect_sqlite(db_path) as conn:
        row = conn.execute(
            """
            SELECT id, username, username_normalized, password_hash, password_salt, status, created_at
            FROM users
            WHERE username_normalized = ?
            """,
            (username_normalized,),
        ).fetchone()
    return dict(row) if row else None


def get_user_by_id(db_path: Path, user_id: str) -> dict[str, Any] | None:
    with connect_sqlite(db_path) as conn:
        row = conn.execute(
            """
            SELECT id, username, created_at
            FROM users
            WHERE id = ?
            """,
            (user_id,),
        ).fetchone()
    return _serialize_user(row) if row else None


def get_user_auth_record_by_id(db_path: Path, user_id: str) -> dict[str, Any] | None:
    with connect_sqlite(db_path) as conn:
        row = conn.execute(
            """
            SELECT id, username, username_normalized, password_hash, password_salt, status, created_at
            FROM users
            WHERE id = ?
            """,
            (user_id,),
        ).fetchone()
    return dict(row) if row else None


def update_user_password(db_path: Path, user_id: str, password_hash: str, password_salt: str) -> None:
    with connect_sqlite(db_path) as conn:
        conn.execute(
            """
            UPDATE users
            SET password_hash = ?, password_salt = ?, updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (password_hash, password_salt, user_id),
        )


def get_account_overview(db_path: Path, user_id: str) -> dict[str, Any]:
    with connect_sqlite(db_path) as conn:
        summary_row = conn.execute(
            """
            SELECT
                SUM(CASE WHEN favorite = 1 THEN 1 ELSE 0 END) AS favorite_count,
                SUM(CASE WHEN mastered = 1 THEN 1 ELSE 0 END) AS mastered_count,
                SUM(practice_count) AS practice_total,
                SUM(CASE WHEN practice_count > 0 THEN 1 ELSE 0 END) AS practiced_question_count
            FROM learning_progress
            WHERE scope_type = 'user' AND scope_id = ?
            """,
            (user_id,),
        ).fetchone()

        recent_rows = conn.execute(
            """
            SELECT
                lp.question_id,
                lp.favorite,
                lp.mastered,
                lp.practice_count,
                lp.last_practiced_at,
                q.question,
                q.domain,
                q.section,
                q.category,
                q.difficulty
            FROM learning_progress lp
            LEFT JOIN questions q ON q.id = lp.question_id
            WHERE lp.scope_type = 'user'
              AND lp.scope_id = ?
              AND lp.practice_count > 0
            ORDER BY lp.last_practiced_at DESC, lp.updated_at DESC
            LIMIT 20
            """,
            (user_id,),
        ).fetchall()

    summary = {
        "favoriteCount": int(summary_row["favorite_count"] or 0),
        "masteredCount": int(summary_row["mastered_count"] or 0),
        "practiceTotal": int(summary_row["practice_total"] or 0),
        "practicedQuestionCount": int(summary_row["practiced_question_count"] or 0),
    }

    recent_records = [
        {
            "questionId": row["question_id"],
            "question": row["question"] or row["question_id"],
            "domain": row["domain"] or "other",
            "section": row["section"] or "",
            "category": row["category"] or "",
            "difficulty": row["difficulty"] or "mid",
            "favorite": bool(row["favorite"]),
            "mastered": bool(row["mastered"]),
            "practiceCount": int(row["practice_count"] or 0),
            "lastPracticedAt": row["last_practiced_at"] or "",
        }
        for row in recent_rows
    ]

    return {
        "ok": True,
        "summary": summary,
        "recentPractice": recent_records,
    }


def create_auth_session(db_path: Path, *, session_id: str, user_id: str, expires_at: str, now_iso: str) -> None:
    with connect_sqlite(db_path) as conn:
        conn.execute(
            """
            INSERT INTO auth_sessions (session_id, user_id, expires_at, last_seen_at, created_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (session_id, user_id, expires_at, now_iso, now_iso),
        )


def get_auth_session_user(db_path: Path, session_id: str, now_iso: str) -> dict[str, Any] | None:
    with connect_sqlite(db_path) as conn:
        row = conn.execute(
            """
            SELECT s.session_id, s.expires_at, u.id, u.username, u.status, u.created_at
            FROM auth_sessions s
            JOIN users u ON u.id = s.user_id
            WHERE s.session_id = ?
            """,
            (session_id,),
        ).fetchone()

        if not row:
            return None
        if (row["status"] or "active") != "active":
            conn.execute("DELETE FROM auth_sessions WHERE session_id = ?", (session_id,))
            return None
        if (row["expires_at"] or "") <= now_iso:
            conn.execute("DELETE FROM auth_sessions WHERE session_id = ?", (session_id,))
            return None

        conn.execute(
            """
            UPDATE auth_sessions
            SET last_seen_at = ?
            WHERE session_id = ?
            """,
            (now_iso, session_id),
        )
        return {
            "id": row["id"],
            "username": row["username"],
            "createdAt": normalize_db_timestamp(row["created_at"]),
        }


def delete_auth_session(db_path: Path, session_id: str) -> None:
    with connect_sqlite(db_path) as conn:
        conn.execute("DELETE FROM auth_sessions WHERE session_id = ?", (session_id,))


def save_resume_session(db_path: Path | str, resume_id: str, record: dict[str, Any]) -> None:
    with connect_sqlite(db_path) as conn:
        conn.execute(
            """
            INSERT INTO resume_sessions (
                resume_id,
                resume_text,
                filename,
                target_role,
                target_stack,
                target_jd,
                selected_domain,
                review_json,
                mode_label,
                ai_error,
                keywords_json,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT(resume_id) DO UPDATE SET
                resume_text=excluded.resume_text,
                filename=excluded.filename,
                target_role=excluded.target_role,
                target_stack=excluded.target_stack,
                target_jd=excluded.target_jd,
                selected_domain=excluded.selected_domain,
                review_json=excluded.review_json,
                mode_label=excluded.mode_label,
                ai_error=excluded.ai_error,
                keywords_json=excluded.keywords_json,
                updated_at=CURRENT_TIMESTAMP
            """,
            (
                resume_id,
                record.get("resume_text", ""),
                record.get("filename", ""),
                record.get("target_role", ""),
                record.get("target_stack", ""),
                record.get("target_jd", ""),
                record.get("selected_domain", ""),
                json.dumps(record.get("review", {}), ensure_ascii=False),
                record.get("mode_label", ""),
                record.get("ai_error", ""),
                json.dumps(record.get("keywords", {}), ensure_ascii=False),
            ),
        )


def get_resume_session(db_path: Path | str, resume_id: str) -> dict[str, Any] | None:
    with connect_sqlite(db_path) as conn:
        row = conn.execute(
            """
            SELECT
                resume_id,
                resume_text,
                filename,
                target_role,
                target_stack,
                target_jd,
                selected_domain,
                review_json,
                mode_label,
                ai_error,
                keywords_json,
                created_at,
                updated_at
            FROM resume_sessions
            WHERE resume_id = ?
            """,
            (resume_id,),
        ).fetchone()

    if not row:
        return None

    return {
        "resume_text": row["resume_text"] or "",
        "filename": row["filename"] or "",
        "target_role": row["target_role"] or "",
        "target_stack": row["target_stack"] or "",
        "target_jd": row["target_jd"] or "",
        "selected_domain": row["selected_domain"] or "",
        "review": json.loads(row["review_json"] or "{}"),
        "mode_label": row["mode_label"] or "",
        "ai_error": row["ai_error"] or "",
        "keywords": json.loads(row["keywords_json"] or "{}"),
    }


def _serialize_user(row: sqlite3.Row | None) -> dict[str, Any] | None:
    if row is None:
        return None
    return {
        "id": row["id"],
        "username": row["username"],
        "createdAt": normalize_db_timestamp(row["created_at"]),
    }


def normalize_db_timestamp(value: str | None) -> str:
    if not value:
        return ""

    raw = str(value).strip()
    if not raw:
        return ""

    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return raw

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).isoformat()
